apiVersion: apps/v1
kind: Deployment
metadata:
  name: sup_backend
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: sup_backend
  template:
    metadata:
      labels:
        app: sup_backend
    spec:
      containers:
      - image: 10.0.16.211:5000/storageup/sup_backend
        name: sup_backend
        ports:
        - containerPort: 80
