apiVersion: apps/v1
kind: Deployment
metadata:
  name: sup-backend
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: sup-backend
  template:
    metadata:
      labels:
        app: sup-backend
    spec:
      containers:
      - image: 10.0.16.211:5000/storageup/sup_backend
        name: sup-backend
        ports:
        - containerPort: 80
        imagePullSecrets:
          - name: regcred2
