apiVersion: apps/v1
kind: Deployment
metadata:
  name: sup-backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: sup-backend
  template:
    metadata:
      labels:
        app: sup-backend
    spec:
      containers:
      - name: sup-backend
        image: 10.0.16.211:5000/storageup/sup_backend:latest
        ports:
          - name: http
            containerPort: 80
        restartPolicy: Always
        resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      imagePullSecrets:
      - name: regcred2
